### ISSUE TITLE
PR taking to long to be merged 

### ISSUE THREAD

**Issue by Omar-Khas** [education/GitHubGraduation-2022#6705]
It's been 2hrs since my PR changes have been approved but until now none of the reviewers have checked if I'm compliant with the COC. I've checked other people's PRs and they are being merged after an hour or less. OtherPRs have been merged although they've been created later than mine. Anyone knows if there's something I can or should do other than waiting? Here's a link to my PR:
[https://github.com/education/GitHubGraduation-2022/pull/6193#pullrequestreview-980811134](https://github.com/orgs/github-community/discussions/url)

**Comment by seia-soto** [comment]
Not PRs of every body here are merged immediately right after their PRs being flagged as ready to merge. It's because reviewers are human just like us, not kind of bot. Eventually, you need to wait for reviewers.

You can check out the merge status on following url:
- https://github.com/education/GitHubGraduation-2022/pulls?q=is%3Apr+is%3Amerged+sort%3Acreated-desc

**Comment by jackgraddon** [comment]
Its been 18 hours for me, just wait your turn.

**Comment by PitamahBhishma-0** [comment]
It's been 3 days and no update on PR .......

**Comment by wu-json** [comment]
> It's been 3 days and no update on PR .......

Same here :(
